## Scalar operations 

In [1]:
import dask.array as da

In [2]:
my_arr = da.random.randint(10, size=20, chunks=3)

In [3]:
my_arr.compute()

array([1, 8, 3, 9, 7, 4, 5, 9, 5, 5, 1, 8, 0, 8, 2, 9, 6, 1, 0, 5])

In [4]:
my_hundred_arr = my_arr + 100
my_hundred_arr.compute()

array([101, 108, 103, 109, 107, 104, 105, 109, 105, 105, 101, 108, 100,
       108, 102, 109, 106, 101, 100, 105])

In [5]:
(my_arr * (-1)).compute()

array([-1, -8, -3, -9, -7, -4, -5, -9, -5, -5, -1, -8,  0, -8, -2, -9, -6,
       -1,  0, -5])

## Reductions

In [8]:
dask_sum = my_arr.sum()
dask_sum

dask.array<sum-aggregate, shape=(), dtype=int64, chunksize=()>

In [11]:
my_arr.compute()

array([1, 8, 3, 9, 7, 4, 5, 9, 5, 5, 1, 8, 0, 8, 2, 9, 6, 1, 0, 5])

In [9]:
dask_sum.compute()

96

In [12]:
my_ones_arr = da.ones((10,10), chunks=2, dtype=int)

In [13]:
my_ones_arr.compute()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [14]:
my_ones_arr.mean(axis=0).compute()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
my_custom_array = da.random.randint(10, size=(4,4), chunks=(1,4))

In [16]:
my_custom_array.compute()

array([[7, 1, 4, 4],
       [1, 5, 5, 5],
       [9, 0, 2, 8],
       [1, 8, 8, 0]])

In [17]:
my_custom_array.mean(axis=0).compute()

array([4.5 , 3.5 , 4.75, 4.25])

In [18]:
my_custom_array.mean(axis=1).compute()

array([4.  , 4.  , 4.75, 4.25])

## Slicing

In [19]:
my_custom_array[1:3, 2:4]

dask.array<getitem, shape=(2, 2), dtype=int64, chunksize=(1, 2)>

In [20]:
my_custom_array[1:3, 2:4].compute()

array([[5, 5],
       [2, 8]])

## Broadcasting

In [21]:
my_custom_array.compute()

array([[7, 1, 4, 4],
       [1, 5, 5, 5],
       [9, 0, 2, 8],
       [1, 8, 8, 0]])

In [23]:
my_small_arr = da.ones(4, chunks=2)
my_small_arr.compute()

array([1., 1., 1., 1.])

In [24]:
brd_example1 = da.add(my_custom_array, my_small_arr)

In [26]:
# [[7, 1, 4, 4], + [[1, 1, 1, 1]
#  [1, 5, 5, 5],   [1, 1, 1, 1]
#  [9, 0, 2, 8],   [1, 1, 1, 1]
#  [1, 8, 8, 0]]   [1, 1, 1, 1]]
brd_example1.compute()

array([[ 8.,  2.,  5.,  5.],
       [ 2.,  6.,  6.,  6.],
       [10.,  1.,  3.,  9.],
       [ 2.,  9.,  9.,  1.]])

In [27]:
ten_arr = da.full_like(my_small_arr, 10)

In [28]:
ten_arr.compute()

array([10., 10., 10., 10.])

In [29]:
brd_example2 = da.add(my_custom_array, ten_arr)

In [30]:
brd_example2.compute()

array([[17., 11., 14., 14.],
       [11., 15., 15., 15.],
       [19., 10., 12., 18.],
       [11., 18., 18., 10.]])

## Reshaping

In [31]:
my_custom_array.shape

(4, 4)

In [32]:
custom_arr_1d = my_custom_array.reshape(16)

In [33]:
custom_arr_1d

dask.array<reshape, shape=(16,), dtype=int64, chunksize=(4,)>

In [34]:
custom_arr_1d.compute()

array([7, 1, 4, 4, 1, 5, 5, 5, 9, 0, 2, 8, 1, 8, 8, 0])

# Stacking

In [35]:
stacked_arr = da.stack([brd_example1, brd_example2])

In [36]:
stacked_arr.compute()

array([[[ 8.,  2.,  5.,  5.],
        [ 2.,  6.,  6.,  6.],
        [10.,  1.,  3.,  9.],
        [ 2.,  9.,  9.,  1.]],

       [[17., 11., 14., 14.],
        [11., 15., 15., 15.],
        [19., 10., 12., 18.],
        [11., 18., 18., 10.]]])

In [37]:
another_stacked = da.stack([brd_example1, brd_example2], axis=1)

In [38]:
another_stacked.compute()

array([[[ 8.,  2.,  5.,  5.],
        [17., 11., 14., 14.]],

       [[ 2.,  6.,  6.,  6.],
        [11., 15., 15., 15.]],

       [[10.,  1.,  3.,  9.],
        [19., 10., 12., 18.]],

       [[ 2.,  9.,  9.,  1.],
        [11., 18., 18., 10.]]])

# Concatenate

In [39]:
concate_arr = da.concatenate([brd_example1, brd_example2])

In [40]:
concate_arr.compute()

array([[ 8.,  2.,  5.,  5.],
       [ 2.,  6.,  6.,  6.],
       [10.,  1.,  3.,  9.],
       [ 2.,  9.,  9.,  1.],
       [17., 11., 14., 14.],
       [11., 15., 15., 15.],
       [19., 10., 12., 18.],
       [11., 18., 18., 10.]])

In [41]:
another_concate_arr = da.concatenate([brd_example1, brd_example2],axis=1)

In [42]:
another_concate_arr.compute()

array([[ 8.,  2.,  5.,  5., 17., 11., 14., 14.],
       [ 2.,  6.,  6.,  6., 11., 15., 15., 15.],
       [10.,  1.,  3.,  9., 19., 10., 12., 18.],
       [ 2.,  9.,  9.,  1., 11., 18., 18., 10.]])